// wrapObject.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Shroud Project Developers.
// See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapObject.h
 * \brief Shroud generated wrapper for Object class
 */
// For C users and C++ implementation

#ifndef WRAPOBJECT_H
#define WRAPOBJECT_H

// shroud
#include "typesShared.h"

// splicer begin class.Object.CXX_declarations
// splicer end class.Object.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.Object.C_declarations
// splicer end class.Object.C_declarations

SHA_Object * SHA_Object_ctor(SHA_Object *SHC_rv);

void SHA_Object_ctor_bufferify(SHA_Object *SHC_rv);

void SHA_Object_dtor(SHA_Object * self);

SHA_Object_shared * SHA_Object_createChildA(SHA_Object * self,
    SHA_Object_shared *SHC_rv);

void SHA_Object_createChildA_bufferify(SHA_Object * self,
    SHA_Object_shared *SHC_rv);

SHA_Object_shared * SHA_Object_createChildB(SHA_Object * self,
    SHA_Object_shared *SHC_rv);

void SHA_Object_createChildB_bufferify(SHA_Object * self,
    SHA_Object_shared *SHC_rv);

void SHA_Object_replaceChildB(SHA_Object * self,
    SHA_Object_shared *child);

#ifdef __cplusplus
}
#endif

#endif  // WRAPOBJECT_H
