// wrapObject_weak.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// cxx_header
#include "shared.hpp"
// shroud
#include <memory>
#include <cstddef>
#include "wrapObject_weak.h"

// splicer begin class.Object.CXX_definitions
// splicer end class.Object.CXX_definitions

extern "C" {

// splicer begin class.Object.C_definitions
// splicer end class.Object.C_definitions

// ----------------------------------------
// Function:  Object
// Statement: c_ctor_shadow_capptr_weak
SHA_Object_weak * SHA_Object_weak_ctor(SHA_Object_weak *SHC_rv)
{
    // splicer begin class.Object.method.ctor
    std::shared_ptr<Object> *SHC_rv_shared =
        new std::shared_ptr<Object>;
    *SHC_rv_shared =  std::make_shared<Object>();
    SHC_rv->addr = static_cast<void *>(SHC_rv_shared);
    SHC_rv->idtor = 7;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    return SHC_rv;
    // splicer end class.Object.method.ctor
}

// ----------------------------------------
// Function:  Object
// Statement: f_ctor_shadow_capsule_weak
void SHA_Object_weak_ctor_bufferify(SHA_Object_weak *SHC_rv)
{
    // splicer begin class.Object.method.ctor_bufferify
    std::weak_ptr<Object> *SHCXX_rv = new std::weak_ptr<Object>;
    SHC_rv->addr = static_cast<void *>(SHCXX_rv);
    SHC_rv->idtor = 7;
    SHC_rv->cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
    // splicer end class.Object.method.ctor_bufferify
}

// ----------------------------------------
// Function:  ~Object
// Statement: c_dtor
void SHA_Object_weak_dtor(SHA_Object_weak * self)
{
    std::weak_ptr<Object> *SH_this =
        static_cast<std::weak_ptr<Object> *>(self->addr);
    // splicer begin class.Object.method.dtor
    if (self->cmemflags & SWIG_MEM_OWN) {
        delete SH_this;
    }
    self->addr = nullptr;
    self->idtor = 0;
    self->cmemflags = 0;
    // splicer end class.Object.method.dtor
}

// ----------------------------------------
// Function:  long use_count
// Statement: c_function_native
long SHA_Object_weak_use_count(SHA_Object_weak * self)
{
    std::weak_ptr<Object> *SH_this =
        static_cast<std::weak_ptr<Object> *>(self->addr);
    // splicer begin class.Object.method.use_count
    long SHC_rv = SH_this->use_count();
    return SHC_rv;
    // splicer end class.Object.method.use_count
}

}  // extern "C"
