// wrapShape.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapShape.h
 * \brief Shroud generated wrapper for Shape class
 */
// For C users and C++ implementation

#ifndef WRAPSHAPE_H
#define WRAPSHAPE_H

// shroud
#include "typesclasses.h"

// splicer begin class.Shape.CXX_declarations
// splicer end class.Shape.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin class.Shape.C_declarations
// splicer end class.Shape.C_declarations

CLA_Shape * CLA_Shape_ctor(CLA_Shape *SHC_rv);

void CLA_Shape_ctor_bufferify(CLA_Shape *SHC_rv);

void CLA_Shape_dtor(CLA_Shape * self);

int CLA_Shape_get_ivar(const CLA_Shape * self);

#ifdef __cplusplus
}
#endif

#endif  // WRAPSHAPE_H
