// wrapInnerNamespace_InnerClass1.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// shroud
#include "wrapInnerNamespace_InnerClass1.h"

// splicer begin namespace.InnerNamespace.class.InnerClass1.CXX_definitions
// splicer end namespace.InnerNamespace.class.InnerClass1.CXX_definitions

extern "C" {

// splicer begin namespace.InnerNamespace.class.InnerClass1.C_definitions
// splicer end namespace.InnerNamespace.class.InnerClass1.C_definitions

// ----------------------------------------
// Function:  void MemberFunction2
// Statement: c_subroutine
void TES_inner_namespace_inner_class1_member_function2(
    TES_inner_namespace_inner_class1 * self)
{
    InnerNamespace::InnerClass1 *SH_this =
        static_cast<InnerNamespace::InnerClass1 *>(self->addr);
    // splicer begin namespace.InnerNamespace.class.InnerClass1.method.MemberFunction2
    SH_this->MemberFunction2();
    // splicer end namespace.InnerNamespace.class.InnerClass1.method.MemberFunction2
}

// Generated by getter/setter
// ----------------------------------------
// Function:  int get_MemberVariable2 +intent(getter)
// Statement: f_getter_native
int TES_inner_namespace_inner_class1_get_member_variable2(
    TES_inner_namespace_inner_class1 * self)
{
    InnerNamespace::InnerClass1 *SH_this =
        static_cast<InnerNamespace::InnerClass1 *>(self->addr);
    // splicer begin namespace.InnerNamespace.class.InnerClass1.method.get_MemberVariable2
    return SH_this->MemberVariable2;
    // splicer end namespace.InnerNamespace.class.InnerClass1.method.get_MemberVariable2
}

// Generated by getter/setter
// ----------------------------------------
// Function:  void set_MemberVariable2 +intent(setter)
// Statement: f_setter
// ----------------------------------------
// Argument:  int val +intent(setter)
// Statement: f_setter_native
void TES_inner_namespace_inner_class1_set_member_variable2(
    TES_inner_namespace_inner_class1 * self, int val)
{
    InnerNamespace::InnerClass1 *SH_this =
        static_cast<InnerNamespace::InnerClass1 *>(self->addr);
    // splicer begin namespace.InnerNamespace.class.InnerClass1.method.set_MemberVariable2
    SH_this->MemberVariable2 = val;
    // splicer end namespace.InnerNamespace.class.InnerClass1.method.set_MemberVariable2
}

}  // extern "C"
