// utilownership.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//

// typemap
#include "ownership.hpp"
// shroud
#include "typesownership.h"
#include <cstddef>
#include <cstring>


#ifdef __cplusplus
extern "C" {
#endif

// helper copy_array
// Copy std::vector into array c_var(c_var_size).
// Then release std::vector.
// Called from Fortran.
void OWN_ShroudCopyArray(OWN_SHROUD_array *data, void *c_var, 
    size_t c_var_size)
{
    const void *cxx_var = data->base_addr;
    int n = c_var_size < data->size ? c_var_size : data->size;
    n *= data->elem_len;
    std::memcpy(c_var, cxx_var, n);
}

// Release library allocated memory.
void OWN_SHROUD_memory_destructor(OWN_SHROUD_capsule_data *cap)
{
    void *ptr = cap->addr;
    switch (cap->idtor) {
    case 0:   // --none--
    {
        // Nothing to delete
        break;
    }
    case 1:   // Class1
    {
        Class1 *cxx_ptr = reinterpret_cast<Class1 *>(ptr);
        delete cxx_ptr;
        break;
    }
    case 2:   // int
    {
        int *cxx_ptr = reinterpret_cast<int *>(ptr);
        free(cxx_ptr);
        break;
    }
    default:
    {
        // Unexpected case in destructor
        break;
    }
    }
    cap->addr = nullptr;
    cap->idtor = 0;  // avoid deleting again
}

// Statement: f_operator_assignment_shadow
// Class1 = Class1
void OWN_Class1_assign_Class1(OWN_Class1 *lhs_capsule,
    OWN_Class1 *rhs_capsule)
{
    if (lhs_capsule->addr == nullptr) {
        /* LHS is unassigned */
        if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
            // Capture pointer from RHS, clear 'moving' flag.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = rhs_capsule->idtor;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
        } else {
            // Aliasing another class; clear ownership.
            lhs_capsule->addr = rhs_capsule->addr;
            lhs_capsule->idtor = 0;
            lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_OWN;
        }
    } else if (rhs_capsule->addr == nullptr) {
        // Replace LHS with a null pointer.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            OWN_SHROUD_memory_destructor(
                (OWN_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = nullptr;
        lhs_capsule->idtor = 0;
        lhs_capsule->cmemflags = 0;
    } else if (lhs_capsule->addr == rhs_capsule->addr) {
        // Lhs-assignment: ignore.
    } else if (rhs_capsule->cmemflags & SWIG_MEM_RVALUE) {
        // Transferred ownership from a variable that's about to be lost.
        // Move-assign and delete the transient data.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            OWN_SHROUD_memory_destructor(
                (OWN_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    } else {
        // RHS shouldn't be deleted, alias to LHS.
        if (lhs_capsule->cmemflags & SWIG_MEM_OWN) {
            OWN_SHROUD_memory_destructor(
                (OWN_SHROUD_capsule_data *) lhs_capsule);
        }
        lhs_capsule->addr = rhs_capsule->addr;
        lhs_capsule->idtor = rhs_capsule->idtor;
        lhs_capsule->cmemflags = rhs_capsule->cmemflags & ~SWIG_MEM_RVALUE;
    }
}

#ifdef __cplusplus
}
#endif
