// typesreferences.h
// This file is generated by Shroud 0.11.0. Do not edit.
// Copyright (c) 2017-2020, Lawrence Livermore National Security, LLC and
// other Shroud Project Developers.
// See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
// For C users and C++ implementation

#ifndef TYPESREFERENCES_H
#define TYPESREFERENCES_H


#ifdef __cplusplus
extern "C" {
#endif

// helper capsule_REF_ArrayWrapper
struct s_REF_ArrayWrapper {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_REF_ArrayWrapper REF_ArrayWrapper;

// helper capsule_data_helper
struct s_REF_SHROUD_capsule_data {
    void *addr;     /* address of C++ memory */
    int idtor;      /* index of destructor */
};
typedef struct s_REF_SHROUD_capsule_data REF_SHROUD_capsule_data;

void REF_SHROUD_memory_destructor(REF_SHROUD_capsule_data *cap);

#ifdef __cplusplus
}
#endif

#endif  // TYPESREFERENCES_H
