! wrapftestapi.f
! This file is generated by Shroud nowrite-version. Do not edit.
! Copyright Shroud Project Developers. See LICENSE file for details.
!
! SPDX-License-Identifier: (BSD-3-Clause)
!
!>
!! \file wrapftestapi.f
!! \brief Shroud generated wrapper for testapi library
!<
! splicer begin file_top
! splicer end file_top
module testapi_mod
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! helper capsule_data
    type, bind(C) :: TES_SHROUD_capsule_data
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
        integer(C_INT) :: cmemflags = 0   ! memory flags
    end type TES_SHROUD_capsule_data

    type TOPCLASS1
        type(TES_SHROUD_capsule_data) :: cxxmem = &
            TES_SHROUD_capsule_data()
        ! splicer begin class.TopClass1.component_part
        ! splicer end class.TopClass1.component_part
    contains
        procedure :: MEMBERFUNCTION1 => TOPCLASS1_MEMBERFUNCTION1
        procedure :: GET_MEMBERVARIABLE1 => TOPCLASS1_GET_MEMBERVARIABLE1
        procedure :: SET_MEMBERVARIABLE1 => TOPCLASS1_SET_MEMBERVARIABLE1
        procedure :: get_instance => TOPCLASS1_get_instance
        procedure :: set_instance => TOPCLASS1_set_instance
        procedure :: associated => TOPCLASS1_associated
        ! splicer begin class.TopClass1.type_bound_procedure_part
        ! splicer end class.TopClass1.type_bound_procedure_part
    end type TOPCLASS1

    interface operator (.eq.)
        module procedure TOPCLASS1_eq
    end interface

    interface operator (.ne.)
        module procedure TOPCLASS1_ne
    end interface

    interface assignment (=)
        module procedure TOPCLASS1_assign_TopClass1
    end interface

    interface

        ! ----------------------------------------
        ! Function:  void MemberFunction1
        ! Statement: f_subroutine
        subroutine c_TOPCLASS1_MEMBERFUNCTION1(self) &
                bind(C, name="TES_TOPCLASS1_MEMBERFUNCTION1")
            import :: TES_SHROUD_capsule_data
            implicit none
            type(TES_SHROUD_capsule_data), intent(IN) :: self
        end subroutine c_TOPCLASS1_MEMBERFUNCTION1

        ! Generated by getter/setter
        ! ----------------------------------------
        ! Function:  int get_MemberVariable1 +intent(getter)
        ! Statement: f_getter_native
        function c_TOPCLASS1_GET_MEMBERVARIABLE1(self) &
                result(SHT_rv) &
                bind(C, name="TES_TOPCLASS1_GET_MEMBERVARIABLE1")
            use iso_c_binding, only : C_INT
            import :: TES_SHROUD_capsule_data
            implicit none
            type(TES_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT) :: SHT_rv
        end function c_TOPCLASS1_GET_MEMBERVARIABLE1

        ! Generated by getter/setter
        ! ----------------------------------------
        ! Function:  void set_MemberVariable1 +intent(setter)
        ! Statement: f_setter
        ! ----------------------------------------
        ! Argument:  int val +intent(setter)
        ! Statement: f_setter_native
        subroutine c_TOPCLASS1_SET_MEMBERVARIABLE1(self, val) &
                bind(C, name="TES_TOPCLASS1_SET_MEMBERVARIABLE1")
            use iso_c_binding, only : C_INT
            import :: TES_SHROUD_capsule_data
            implicit none
            type(TES_SHROUD_capsule_data), intent(IN) :: self
            integer(C_INT), value, intent(IN) :: val
        end subroutine c_TOPCLASS1_SET_MEMBERVARIABLE1

        ! ----------------------------------------
        ! Function:  void TopFunction1
        ! Statement: f_subroutine
        subroutine c_TOPFUNCTION1() &
                bind(C, name="TES_TOPFUNCTION1")
            implicit none
        end subroutine c_TOPFUNCTION1
    end interface

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! ----------------------------------------
    ! Function:  void MemberFunction1
    ! Statement: f_subroutine
    subroutine TOPCLASS1_MEMBERFUNCTION1(obj)
        class(TOPCLASS1), intent(INOUT) :: obj
        ! splicer begin class.TopClass1.method.MEMBERFUNCTION1
        call c_TOPCLASS1_MEMBERFUNCTION1(obj%cxxmem)
        ! splicer end class.TopClass1.method.MEMBERFUNCTION1
    end subroutine TOPCLASS1_MEMBERFUNCTION1

    ! Generated by getter/setter
    ! ----------------------------------------
    ! Function:  int get_MemberVariable1 +intent(getter)
    ! Statement: f_getter_native
    function TOPCLASS1_GET_MEMBERVARIABLE1(obj) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        class(TOPCLASS1), intent(INOUT) :: obj
        integer(C_INT) :: SHT_rv
        ! splicer begin class.TopClass1.method.GET_MEMBERVARIABLE1
        SHT_rv = c_TOPCLASS1_GET_MEMBERVARIABLE1(obj%cxxmem)
        ! splicer end class.TopClass1.method.GET_MEMBERVARIABLE1
    end function TOPCLASS1_GET_MEMBERVARIABLE1

    ! Generated by getter/setter
    ! ----------------------------------------
    ! Function:  void set_MemberVariable1 +intent(setter)
    ! Statement: f_setter
    ! ----------------------------------------
    ! Argument:  int val +intent(setter)
    ! Statement: f_setter_native
    subroutine TOPCLASS1_SET_MEMBERVARIABLE1(obj, val)
        use iso_c_binding, only : C_INT
        class(TOPCLASS1), intent(INOUT) :: obj
        integer(C_INT), value, intent(IN) :: val
        ! splicer begin class.TopClass1.method.SET_MEMBERVARIABLE1
        call c_TOPCLASS1_SET_MEMBERVARIABLE1(obj%cxxmem, val)
        ! splicer end class.TopClass1.method.SET_MEMBERVARIABLE1
    end subroutine TOPCLASS1_SET_MEMBERVARIABLE1

    ! Return pointer to C++ memory.
    function TOPCLASS1_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(TOPCLASS1), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function TOPCLASS1_get_instance

    subroutine TOPCLASS1_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(TOPCLASS1), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine TOPCLASS1_set_instance

    function TOPCLASS1_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(TOPCLASS1), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function TOPCLASS1_associated

    ! splicer begin class.TopClass1.additional_functions
    ! splicer end class.TopClass1.additional_functions

    ! ----------------------------------------
    ! Function:  void TopFunction1
    ! Statement: f_subroutine
    subroutine TOPFUNCTION1()
        ! splicer begin function.TOPFUNCTION1
        call c_TOPFUNCTION1()
        ! splicer end function.TOPFUNCTION1
    end subroutine TOPFUNCTION1

    ! Statement: f_operator_assignment_shadow
    ! TopClass1 = TopClass1
    subroutine TOPCLASS1_assign_TopClass1(lhs, rhs)
        use iso_c_binding, only : c_associated, c_f_pointer
        class(TOPCLASS1), intent(INOUT) :: lhs
        type(TOPCLASS1), intent(IN) :: rhs
        interface
            subroutine do_assign(lhs, rhs) bind(C, &
                name="TES_TOPCLASS1_assign_TopClass1")
                import :: TES_SHROUD_capsule_data
                type(TES_SHROUD_capsule_data), intent(INOUT) :: lhs
                type(TES_SHROUD_capsule_data), intent(IN) :: rhs
            end subroutine do_assign
        end interface
        call do_assign(lhs%cxxmem, rhs%cxxmem)
    end subroutine TOPCLASS1_assign_TopClass1

    ! splicer begin additional_functions
    ! splicer end additional_functions

    function TOPCLASS1_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(TOPCLASS1), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function TOPCLASS1_eq

    function TOPCLASS1_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(TOPCLASS1), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function TOPCLASS1_ne

end module testapi_mod
