! top.f
! This file is generated by Shroud nowrite-version. Do not edit.
! Copyright (c) 2017-2024, Lawrence Livermore National Security, LLC and
! other Shroud Project Developers.
! See the top-level COPYRIGHT file for details.
!
! SPDX-License-Identifier: (BSD-3-Clause)
!
!>
!! \file top.f
!! \brief Shroud generated wrapper for testnames library
!<
! splicer begin file_top
! splicer end file_top
module top_module
    use iso_c_binding, only : C_INT, C_NULL_PTR, C_PTR
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! helper capsule_data_helper
    type, bind(C) :: TES_SHROUD_capsule_data
        type(C_PTR) :: addr = C_NULL_PTR  ! address of C++ memory
        integer(C_INT) :: idtor = 0       ! index of destructor
    end type TES_SHROUD_capsule_data

    !  enum Color
    integer, parameter :: color = C_INT
    ! splicer begin enum.Color
    integer(color), parameter :: red = 0
    integer(color), parameter :: blue = 1
    integer(color), parameter :: white = 2
    ! splicer end enum.Color

    type names2
        type(TES_SHROUD_capsule_data) :: cxxmem
        ! splicer begin class.Names2.component_part
        ! splicer end class.Names2.component_part
    contains
        procedure :: get_instance => names2_get_instance
        procedure :: set_instance => names2_set_instance
        procedure :: associated => names2_associated
        ! splicer begin class.Names2.type_bound_procedure_part
        ! splicer end class.Names2.type_bound_procedure_part
    end type names2

    type two_ts_0
        type(TES_SHROUD_capsule_data) :: cxxmem
        ! splicer begin class.twoTs_0.component_part
        ! splicer end class.twoTs_0.component_part
    contains
        procedure :: get_instance => two_ts_0_get_instance
        procedure :: set_instance => two_ts_0_set_instance
        procedure :: associated => two_ts_0_associated
        ! splicer begin class.twoTs_0.type_bound_procedure_part
        ! splicer end class.twoTs_0.type_bound_procedure_part
    end type two_ts_0

    type two_ts_instantiation4
        type(TES_SHROUD_capsule_data) :: cxxmem
        ! splicer begin class.twoTs_instantiation4.component_part
        ! splicer end class.twoTs_instantiation4.component_part
    contains
        procedure :: get_instance_instantiation4 => two_ts_instantiation4_get_instance_instantiation4
        procedure :: set_instance_instantiation4 => two_ts_instantiation4_set_instance_instantiation4
        procedure :: associated_instantiation4 => two_ts_instantiation4_associated_instantiation4
        ! splicer begin class.twoTs_instantiation4.type_bound_procedure_part
        ! splicer end class.twoTs_instantiation4.type_bound_procedure_part
    end type two_ts_instantiation4

    type Fstruct_as_class
        type(TES_SHROUD_capsule_data) :: cxxmem
        ! splicer begin class.Cstruct_as_class.component_part
        ! splicer end class.Cstruct_as_class.component_part
    contains
        procedure :: get_instance => cstruct_as_class_get_instance
        procedure :: set_instance => cstruct_as_class_set_instance
        procedure :: associated => cstruct_as_class_associated
        procedure :: cstruct_as_class_sum
        ! splicer begin class.Cstruct_as_class.type_bound_procedure_part
        ! splicer end class.Cstruct_as_class.type_bound_procedure_part
    end type Fstruct_as_class

    type, extends(Fstruct_as_class) :: Fstruct_as_subclass
        ! splicer begin class.Cstruct_as_subclass.component_part
        ! splicer end class.Cstruct_as_subclass.component_part
    contains
        procedure :: get_instance => cstruct_as_subclass_get_instance
        procedure :: set_instance => cstruct_as_subclass_set_instance
        procedure :: associated => cstruct_as_subclass_associated
        ! splicer begin class.Cstruct_as_subclass.type_bound_procedure_part
        ! splicer end class.Cstruct_as_subclass.type_bound_procedure_part
    end type Fstruct_as_subclass

    interface operator (.eq.)
        module procedure names2_eq
        module procedure two_ts_0_eq
        module procedure two_ts_instantiation4_eq
        module procedure cstruct_as_class_eq
        module procedure cstruct_as_subclass_eq
    end interface

    interface operator (.ne.)
        module procedure names2_ne
        module procedure two_ts_0_ne
        module procedure two_ts_instantiation4_ne
        module procedure cstruct_as_class_ne
        module procedure cstruct_as_subclass_ne
    end interface

    abstract interface

        subroutine external_funcs_afree(arr) bind(C)
            use iso_c_binding, only : C_DOUBLE
            implicit none
            real(C_DOUBLE), intent(INOUT) :: arr
        end subroutine external_funcs_afree

        subroutine external_funcs_alloc(arr, err) bind(C)
            use iso_c_binding, only : C_DOUBLE, C_INT
            implicit none
            real(C_DOUBLE), intent(INOUT) :: arr
            integer(C_INT), intent(OUT) :: err
        end subroutine external_funcs_alloc

        subroutine external_funcs_assoc(arr, err) bind(C)
            use iso_c_binding, only : C_DOUBLE, C_INT
            implicit none
            real(C_DOUBLE), intent(IN) :: arr
            integer(C_INT), intent(OUT) :: err
        end subroutine external_funcs_assoc

    end interface

    interface

        ! ----------------------------------------
        ! Function:  void getName
        ! Statement: c_subroutine
        ! ----------------------------------------
        ! Argument:  char * name +len(worklen)+len_trim(worktrim)
        ! Statement: c_inout_char*
        subroutine c_get_name(name) &
                bind(C, name="TES_getName")
            use iso_c_binding, only : C_CHAR
            implicit none
            character(kind=C_CHAR), intent(INOUT) :: name(*)
        end subroutine c_get_name

        ! ----------------------------------------
        ! Function:  void getName
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  char * name +len(worklen)+len_trim(worktrim)
        ! Statement: f_inout_char*_buf
        subroutine c_get_name_bufferify(name, SHT_name_len) &
                bind(C, name="TES_getName_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT
            implicit none
            character(kind=C_CHAR), intent(INOUT) :: name(*)
            integer(C_INT), value, intent(IN) :: SHT_name_len
        end subroutine c_get_name_bufferify

        ! ----------------------------------------
        ! Function:  void function1
        ! Statement: f_subroutine
        subroutine YYY_TES_function1() &
                bind(C, name="YYY_TES_function1")
            implicit none
        end subroutine YYY_TES_function1

        ! ----------------------------------------
        ! Function:  void function2
        ! Statement: f_subroutine
        subroutine f_c_name_special() &
                bind(C, name="c_name_special")
            implicit none
        end subroutine f_c_name_special

        ! ----------------------------------------
        ! Function:  void function3a
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int i
        ! Statement: f_in_native
        subroutine YYY_TES_function3a_0(i) &
                bind(C, name="YYY_TES_function3a_0")
            use iso_c_binding, only : C_INT
            implicit none
            integer(C_INT), value, intent(IN) :: i
        end subroutine YYY_TES_function3a_0

        ! ----------------------------------------
        ! Function:  void function3a
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  long i
        ! Statement: f_in_native
        subroutine YYY_TES_function3a_1(i) &
                bind(C, name="YYY_TES_function3a_1")
            use iso_c_binding, only : C_LONG
            implicit none
            integer(C_LONG), value, intent(IN) :: i
        end subroutine YYY_TES_function3a_1

        ! ----------------------------------------
        ! Function:  int function4
        ! Statement: c_function_native
        ! ----------------------------------------
        ! Argument:  const std::string & rv
        ! Statement: c_in_string&
        function YYY_TES_function4(rv) &
                result(SHT_rv) &
                bind(C, name="YYY_TES_function4")
            use iso_c_binding, only : C_CHAR, C_INT
            implicit none
            character(kind=C_CHAR), intent(IN) :: rv(*)
            integer(C_INT) :: SHT_rv
        end function YYY_TES_function4

        ! ----------------------------------------
        ! Function:  int function4
        ! Statement: f_function_native
        ! ----------------------------------------
        ! Argument:  const std::string & rv
        ! Statement: f_in_string&_buf
        function YYY_TES_function4_bufferify(rv, SHT_rv_len) &
                result(SHT_rv) &
                bind(C, name="YYY_TES_function4_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT
            implicit none
            character(kind=C_CHAR), intent(IN) :: rv(*)
            integer(C_INT), value, intent(IN) :: SHT_rv_len
            integer(C_INT) :: SHT_rv
        end function YYY_TES_function4_bufferify

        ! ----------------------------------------
        ! Function:  void function5 +name(fiveplus)
        ! Statement: f_subroutine
        subroutine YYY_TES_fiveplus() &
                bind(C, name="YYY_TES_fiveplus")
            implicit none
        end subroutine YYY_TES_fiveplus

        ! ----------------------------------------
        ! Function:  void TestMultilineSplicer
        ! Statement: c_subroutine
        ! ----------------------------------------
        ! Argument:  std::string & name
        ! Statement: c_inout_string&
        ! ----------------------------------------
        ! Argument:  int * value +intent(out)
        ! Statement: c_out_native*
        subroutine c_test_multiline_splicer(name, value) &
                bind(C, name="TES_TestMultilineSplicer")
            use iso_c_binding, only : C_CHAR, C_INT
            implicit none
            character(kind=C_CHAR), intent(INOUT) :: name(*)
            integer(C_INT), intent(OUT) :: value
        end subroutine c_test_multiline_splicer

        ! ----------------------------------------
        ! Function:  void TestMultilineSplicer
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  std::string & name
        ! Statement: f_inout_string&_buf
        ! ----------------------------------------
        ! Argument:  int * value +intent(out)
        ! Statement: f_out_native*
        subroutine c_test_multiline_splicer_bufferify(name, &
                SHT_name_len, value) &
                bind(C, name="TES_TestMultilineSplicer_bufferify")
            use iso_c_binding, only : C_CHAR, C_INT
            implicit none
            character(kind=C_CHAR), intent(INOUT) :: name(*)
            integer(C_INT), value, intent(IN) :: SHT_name_len
            integer(C_INT), intent(OUT) :: value
        end subroutine c_test_multiline_splicer_bufferify

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void FunctionTU
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int arg1
        ! Statement: f_in_native
        ! ----------------------------------------
        ! Argument:  long arg2
        ! Statement: f_in_native
        subroutine f_c_name_instantiation1(arg1, arg2) &
                bind(C, name="c_name_instantiation1")
            use iso_c_binding, only : C_INT, C_LONG
            implicit none
            integer(C_INT), value, intent(IN) :: arg1
            integer(C_LONG), value, intent(IN) :: arg2
        end subroutine f_c_name_instantiation1

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  void FunctionTU
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  float arg1
        ! Statement: f_in_native
        ! ----------------------------------------
        ! Argument:  double arg2
        ! Statement: f_in_native
        subroutine c_function_tu_instantiation2(arg1, arg2) &
                bind(C, name="TES_FunctionTU_instantiation2")
            use iso_c_binding, only : C_DOUBLE, C_FLOAT
            implicit none
            real(C_FLOAT), value, intent(IN) :: arg1
            real(C_DOUBLE), value, intent(IN) :: arg2
        end subroutine c_function_tu_instantiation2

        ! Generated by cxx_template
        ! ----------------------------------------
        ! Function:  int UseImplWorker
        ! Statement: f_function_native
        function c_use_impl_worker_instantiation3() &
                result(SHT_rv) &
                bind(C, name="TES_UseImplWorker_instantiation3")
            use iso_c_binding, only : C_INT
            implicit none
            integer(C_INT) :: SHT_rv
        end function c_use_impl_worker_instantiation3

        ! ----------------------------------------
        ! Function:  int Cstruct_as_class_sum
        ! Statement: f_function_native
        ! ----------------------------------------
        ! Argument:  const Cstruct_as_class * point +pass
        ! Statement: f_in_shadow*
        function c_cstruct_as_class_sum(point) &
                result(SHT_rv) &
                bind(C, name="TES_Cstruct_as_class_sum")
            use iso_c_binding, only : C_INT
            import :: TES_SHROUD_capsule_data
            implicit none
            type(TES_SHROUD_capsule_data), intent(IN) :: point
            integer(C_INT) :: SHT_rv
        end function c_cstruct_as_class_sum

        ! ----------------------------------------
        ! Function:  void external_funcs
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  const char * rdbase
        ! Statement: f_in_char*
        ! ----------------------------------------
        ! Argument:  const char * pkg
        ! Statement: f_in_char*
        ! ----------------------------------------
        ! Argument:  const char * name
        ! Statement: f_in_char*
        ! ----------------------------------------
        ! Argument:  void ( * alloc)(double * arr +intent(inout), int * err +intent(out))
        ! Statement: f_in_procedure
        ! ----------------------------------------
        ! Argument:  void ( * afree)(double * arr +intent(inout))
        ! Statement: f_in_procedure
        ! ----------------------------------------
        ! Argument:  void ( * assoc)(double * arr +intent(in), int * err +intent(out))
        ! Statement: f_in_procedure
        subroutine c_external_funcs(rdbase, pkg, name, alloc, afree, &
                assoc) &
                bind(C, name="TES_external_funcs")
            use iso_c_binding, only : C_CHAR
            import :: external_funcs_afree, external_funcs_alloc, &
                external_funcs_assoc
            implicit none
            character(kind=C_CHAR), intent(IN) :: rdbase(*)
            character(kind=C_CHAR), intent(IN) :: pkg(*)
            character(kind=C_CHAR), intent(IN) :: name(*)
            procedure(external_funcs_alloc) :: alloc
            procedure(external_funcs_afree) :: afree
            procedure(external_funcs_assoc) :: assoc
        end subroutine c_external_funcs

        ! ----------------------------------------
        ! Function:  void bindtest
        ! Statement: f_subroutine
        ! ----------------------------------------
        ! Argument:  int arg1
        ! Statement: f_in_native
        subroutine c_bindtest(arg1) &
                bind(C, name="TES_bindtest")
            use iso_c_binding, only : C_INT
            implicit none
            integer(C_INT), value, intent(IN) :: arg1
        end subroutine c_bindtest
    end interface

    interface function_tu
        module procedure f_name_instantiation1
        module procedure function_tu_instantiation2
    end interface function_tu

    interface generic3
        module procedure F_name_function3a_int
        module procedure F_name_function3a_long
    end interface generic3

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! Return pointer to C++ memory.
    function names2_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(names2), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function names2_get_instance

    subroutine names2_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(names2), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine names2_set_instance

    function names2_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(names2), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function names2_associated

    ! splicer begin class.Names2.additional_functions
    ! splicer end class.Names2.additional_functions

    ! Return pointer to C++ memory.
    function two_ts_0_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(two_ts_0), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function two_ts_0_get_instance

    subroutine two_ts_0_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(two_ts_0), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine two_ts_0_set_instance

    function two_ts_0_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(two_ts_0), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function two_ts_0_associated

    ! splicer begin class.twoTs_0.additional_functions
    ! splicer end class.twoTs_0.additional_functions

    ! Return pointer to C++ memory.
    function two_ts_instantiation4_get_instance_instantiation4(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(two_ts_instantiation4), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function two_ts_instantiation4_get_instance_instantiation4

    subroutine two_ts_instantiation4_set_instance_instantiation4(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(two_ts_instantiation4), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine two_ts_instantiation4_set_instance_instantiation4

    function two_ts_instantiation4_associated_instantiation4(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(two_ts_instantiation4), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function two_ts_instantiation4_associated_instantiation4

    ! splicer begin class.twoTs_instantiation4.additional_functions
    ! splicer end class.twoTs_instantiation4.additional_functions

    ! Return pointer to C++ memory.
    function cstruct_as_class_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(Fstruct_as_class), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function cstruct_as_class_get_instance

    subroutine cstruct_as_class_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(Fstruct_as_class), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine cstruct_as_class_set_instance

    function cstruct_as_class_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(Fstruct_as_class), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function cstruct_as_class_associated

    ! splicer begin class.Cstruct_as_class.additional_functions
    ! splicer end class.Cstruct_as_class.additional_functions

    ! Return pointer to C++ memory.
    function cstruct_as_subclass_get_instance(obj) result (cxxptr)
        use iso_c_binding, only: C_PTR
        class(Fstruct_as_subclass), intent(IN) :: obj
        type(C_PTR) :: cxxptr
        cxxptr = obj%cxxmem%addr
    end function cstruct_as_subclass_get_instance

    subroutine cstruct_as_subclass_set_instance(obj, cxxmem)
        use iso_c_binding, only: C_PTR
        class(Fstruct_as_subclass), intent(INOUT) :: obj
        type(C_PTR), intent(IN) :: cxxmem
        obj%cxxmem%addr = cxxmem
        obj%cxxmem%idtor = 0
    end subroutine cstruct_as_subclass_set_instance

    function cstruct_as_subclass_associated(obj) result (rv)
        use iso_c_binding, only: c_associated
        class(Fstruct_as_subclass), intent(IN) :: obj
        logical rv
        rv = c_associated(obj%cxxmem%addr)
    end function cstruct_as_subclass_associated

    ! splicer begin class.Cstruct_as_subclass.additional_functions
    ! splicer end class.Cstruct_as_subclass.additional_functions

    ! ----------------------------------------
    ! Function:  void getName
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  char * name +len(worklen)+len_trim(worktrim)
    ! Statement: f_inout_char*_buf
    subroutine get_name(name)
        use iso_c_binding, only : C_INT
        character(len=*), intent(INOUT) :: name
        ! splicer begin function.get_name
        integer(C_INT) SHT_name_len
        SHT_name_len = len(name, kind=C_INT)
        call c_get_name_bufferify(name, SHT_name_len)
        ! splicer end function.get_name
    end subroutine get_name

    ! ----------------------------------------
    ! Function:  void function1
    ! Statement: f_subroutine
    subroutine testnames_function1()
        ! splicer begin function.function1
        call YYY_TES_function1()
        ! splicer end function.function1
    end subroutine testnames_function1

    ! ----------------------------------------
    ! Function:  void function2
    ! Statement: f_subroutine
    subroutine f_name_special()
        ! splicer begin function.function2
        call f_c_name_special()
        ! splicer end function.function2
    end subroutine f_name_special

    ! ----------------------------------------
    ! Function:  void function3a
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int i
    ! Statement: f_in_native
    subroutine F_name_function3a_int(i)
        use iso_c_binding, only : C_INT
        integer(C_INT), value, intent(IN) :: i
        ! splicer begin function.function3a_0
        call YYY_TES_function3a_0(i)
        ! splicer end function.function3a_0
    end subroutine F_name_function3a_int

    ! ----------------------------------------
    ! Function:  void function3a
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  long i
    ! Statement: f_in_native
    subroutine F_name_function3a_long(i)
        use iso_c_binding, only : C_LONG
        integer(C_LONG), value, intent(IN) :: i
        ! splicer begin function.function3a_1
        call YYY_TES_function3a_1(i)
        ! splicer end function.function3a_1
    end subroutine F_name_function3a_long

    ! ----------------------------------------
    ! Function:  int function4
    ! Statement: f_function_native
    ! ----------------------------------------
    ! Argument:  const std::string & rv
    ! Statement: f_in_string&_buf
    function testnames_function4(rv) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        character(len=*), intent(IN) :: rv
        integer(C_INT) :: SHT_rv
        ! splicer begin function.function4
        integer(C_INT) SHT_rv_len
        SHT_rv_len = len(rv, kind=C_INT)
        SHT_rv = YYY_TES_function4_bufferify(rv, SHT_rv_len)
        ! splicer end function.function4
    end function testnames_function4

    ! ----------------------------------------
    ! Function:  void function5 +name(fiveplus)
    ! Statement: f_subroutine
    subroutine testnames_fiveplus()
        ! splicer begin function.fiveplus
        call YYY_TES_fiveplus()
        ! splicer end function.fiveplus
    end subroutine testnames_fiveplus

    ! ----------------------------------------
    ! Function:  void TestMultilineSplicer
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  std::string & name
    ! Statement: f_inout_string&_buf
    ! ----------------------------------------
    ! Argument:  int * value +intent(out)
    ! Statement: f_out_native*
    !>
    !! Use std::string argument to get bufferified function.
    !<
    subroutine test_multiline_splicer(name, value)
        use iso_c_binding, only : C_INT
        character(len=*), intent(INOUT) :: name
        integer(C_INT), intent(OUT) :: value
        ! splicer begin function.test_multiline_splicer
        ! line 1
        ! line 2
        ! splicer end function.test_multiline_splicer
    end subroutine test_multiline_splicer

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void FunctionTU
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int arg1
    ! Statement: f_in_native
    ! ----------------------------------------
    ! Argument:  long arg2
    ! Statement: f_in_native
    !>
    !! \brief Function template with two template parameters.
    !!
    !<
    subroutine f_name_instantiation1(arg1, arg2)
        use iso_c_binding, only : C_INT, C_LONG
        integer(C_INT), value, intent(IN) :: arg1
        integer(C_LONG), value, intent(IN) :: arg2
        ! splicer begin function.function_tu_0
        call f_c_name_instantiation1(arg1, arg2)
        ! splicer end function.function_tu_0
    end subroutine f_name_instantiation1

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  void FunctionTU
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  float arg1
    ! Statement: f_in_native
    ! ----------------------------------------
    ! Argument:  double arg2
    ! Statement: f_in_native
    !>
    !! \brief Function template with two template parameters.
    !!
    !<
    subroutine function_tu_instantiation2(arg1, arg2)
        use iso_c_binding, only : C_DOUBLE, C_FLOAT
        real(C_FLOAT), value, intent(IN) :: arg1
        real(C_DOUBLE), value, intent(IN) :: arg2
        ! splicer begin function.function_tu_instantiation2
        call c_function_tu_instantiation2(arg1, arg2)
        ! splicer end function.function_tu_instantiation2
    end subroutine function_tu_instantiation2

    ! Generated by cxx_template
    ! ----------------------------------------
    ! Function:  int UseImplWorker
    ! Statement: f_function_native
    !>
    !! \brief Function which uses a templated T in the implemetation.
    !!
    !<
    function use_impl_worker_instantiation3() &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        integer(C_INT) :: SHT_rv
        ! splicer begin function.use_impl_worker_instantiation3
        SHT_rv = c_use_impl_worker_instantiation3()
        ! splicer end function.use_impl_worker_instantiation3
    end function use_impl_worker_instantiation3

    ! ----------------------------------------
    ! Function:  int Cstruct_as_class_sum
    ! Statement: f_function_native
    ! ----------------------------------------
    ! Argument:  const Cstruct_as_class * point +pass
    ! Statement: f_in_shadow*
    function cstruct_as_class_sum(point) &
            result(SHT_rv)
        use iso_c_binding, only : C_INT
        class(Fstruct_as_class), intent(IN) :: point
        integer(C_INT) :: SHT_rv
        ! splicer begin function.cstruct_as_class_sum
        SHT_rv = c_cstruct_as_class_sum(point%cxxmem)
        ! splicer end function.cstruct_as_class_sum
    end function cstruct_as_class_sum

    ! ----------------------------------------
    ! Function:  void external_funcs
    ! Statement: f_subroutine
    subroutine external_funcs(rdbase, pkg, name, alloc, afree, assoc)
        use iso_c_binding, only : C_NULL_CHAR
        character(len=*), intent(IN) :: rdbase
        character(len=*), intent(IN) :: pkg
        character(len=*), intent(IN) :: name
        procedure(external_funcs_alloc) :: alloc
        procedure(external_funcs_afree) :: afree
        procedure(external_funcs_assoc) :: assoc
        ! splicer begin function.external_funcs
        call c_external_funcs(trim(rdbase)//C_NULL_CHAR, &
            trim(pkg)//C_NULL_CHAR, trim(name)//C_NULL_CHAR, alloc, &
            afree, assoc)
        ! splicer end function.external_funcs
    end subroutine external_funcs

    ! ----------------------------------------
    ! Function:  void bindtest
    ! Statement: f_subroutine
    ! ----------------------------------------
    ! Argument:  int arg1
    ! Statement: f_in_native
    subroutine bindtest(arg1)
        use iso_c_binding, only : C_INT
        integer(C_INT), value, intent(IN) :: arg1
        ! splicer begin function.bindtest
        call c_bindtest(arg1)
        ! splicer end function.bindtest
    end subroutine bindtest

    ! splicer begin additional_functions
    ! splicer end additional_functions

    function names2_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(names2), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function names2_eq

    function names2_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(names2), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function names2_ne

    function two_ts_0_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(two_ts_0), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function two_ts_0_eq

    function two_ts_0_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(two_ts_0), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function two_ts_0_ne

    function two_ts_instantiation4_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(two_ts_instantiation4), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function two_ts_instantiation4_eq

    function two_ts_instantiation4_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(two_ts_instantiation4), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function two_ts_instantiation4_ne

    function cstruct_as_class_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(Fstruct_as_class), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function cstruct_as_class_eq

    function cstruct_as_class_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(Fstruct_as_class), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function cstruct_as_class_ne

    function cstruct_as_subclass_eq(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(Fstruct_as_subclass), intent(IN) ::a,b
        logical :: rv
        if (c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function cstruct_as_subclass_eq

    function cstruct_as_subclass_ne(a,b) result (rv)
        use iso_c_binding, only: c_associated
        type(Fstruct_as_subclass), intent(IN) ::a,b
        logical :: rv
        if (.not. c_associated(a%cxxmem%addr, b%cxxmem%addr)) then
            rv = .true.
        else
            rv = .false.
        endif
    end function cstruct_as_subclass_ne

end module top_module
