// pyUser2type.cpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright (c) 2017-2025, Lawrence Livermore National Security, LLC and
// other Shroud Project Developers.
// See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
#ifdef USE_USER2
#include "pypreprocessmodule.hpp"

// splicer begin class.User2.impl.include
// splicer end class.User2.impl.include

#ifdef __cplusplus
#define SHROUD_UNUSED(param)
#else
#define SHROUD_UNUSED(param) param
#endif

#if PY_MAJOR_VERSION >= 3
#define PyInt_AsLong PyLong_AsLong
#define PyInt_FromLong PyLong_FromLong
#define PyInt_FromSize_t PyLong_FromSize_t
#define PyString_FromString PyUnicode_FromString
#define PyString_FromStringAndSize PyUnicode_FromStringAndSize
#endif

// splicer begin class.User2.impl.C_definition
// splicer end class.User2.impl.C_definition

// splicer begin class.User2.impl.additional_methods
// splicer end class.User2.impl.additional_methods
static void
PY_User2_tp_del (PY_User2 *self)
{
// splicer begin class.User2.type.del
    PY_SHROUD_release_memory(self->idtor, self->obj);
    self->obj = nullptr;
// splicer end class.User2.type.del
}

// ----------------------------------------
// Function:  void exfunc
// Statement: py_subroutine
#ifdef USE_CLASS3_A
static PyObject *
PY_exfunc_0(
  PY_User2 *self,
  PyObject *SHROUD_UNUSED(args),
  PyObject *SHROUD_UNUSED(kwds))
{
// splicer begin class.User2.method.exfunc_0
    self->obj->exfunc();
    Py_RETURN_NONE;
// splicer end class.User2.method.exfunc_0
}
#endif // ifdef USE_CLASS3_A

// ----------------------------------------
// Function:  void exfunc
// Statement: py_subroutine
// ----------------------------------------
// Argument:  int flag
// Statement: py_in_native
#ifndef USE_CLASS3_A
static PyObject *
PY_exfunc_1(
  PY_User2 *self,
  PyObject *args,
  PyObject *kwds)
{
// splicer begin class.User2.method.exfunc_1
    int flag;
    const char *SHT_kwlist[] = {
        "flag",
        nullptr };

    if (!PyArg_ParseTupleAndKeywords(args, kwds, "i:exfunc",
        const_cast<char **>(SHT_kwlist), &flag))
        return nullptr;

    self->obj->exfunc(flag);
    Py_RETURN_NONE;
// splicer end class.User2.method.exfunc_1
}
#endif // ifndef USE_CLASS3_A

static char PY_exfunc__doc__[] =
"documentation"
;

static PyObject *
PY_exfunc(
  PY_User2 *self,
  PyObject *args,
  PyObject *kwds)
{
// splicer begin class.User2.method.exfunc
    Py_ssize_t SHT_nargs = 0;
    if (args != nullptr) SHT_nargs += PyTuple_Size(args);
    if (kwds != nullptr) SHT_nargs += PyDict_Size(args);
    PyObject *rvobj;
#ifdef USE_CLASS3_A
    if (SHT_nargs == 0) {
        rvobj = PY_exfunc_0(self, args, kwds);
        if (!PyErr_Occurred()) {
            return rvobj;
        } else if (! PyErr_ExceptionMatches(PyExc_TypeError)) {
            return rvobj;
        }
        PyErr_Clear();
    }
#endif // ifdef USE_CLASS3_A
#ifndef USE_CLASS3_A
    if (SHT_nargs == 1) {
        rvobj = PY_exfunc_1(self, args, kwds);
        if (!PyErr_Occurred()) {
            return rvobj;
        } else if (! PyErr_ExceptionMatches(PyExc_TypeError)) {
            return rvobj;
        }
        PyErr_Clear();
    }
#endif // ifndef USE_CLASS3_A
    PyErr_SetString(PyExc_TypeError, "wrong arguments multi-dispatch");
    return nullptr;
// splicer end class.User2.method.exfunc
}
// splicer begin class.User2.impl.after_methods
// splicer end class.User2.impl.after_methods
static PyMethodDef PY_User2_methods[] = {
    {"exfunc", (PyCFunction)PY_exfunc, METH_VARARGS|METH_KEYWORDS,
        PY_exfunc__doc__},
    // splicer begin class.User2.PyMethodDef
    // splicer end class.User2.PyMethodDef
    {nullptr,   (PyCFunction)nullptr, 0, nullptr}            /* sentinel */
};

static char User2__doc__[] =
"virtual class"
;

/* static */
PyTypeObject PY_User2_Type = {
    PyVarObject_HEAD_INIT(nullptr, 0)
    "preprocess.User2",                       /* tp_name */
    sizeof(PY_User2),         /* tp_basicsize */
    0,                              /* tp_itemsize */
    /* Methods to implement standard operations */
    (destructor)nullptr,                 /* tp_dealloc */
    (printfunc)nullptr,                   /* tp_print */
    (getattrfunc)nullptr,                 /* tp_getattr */
    (setattrfunc)nullptr,                 /* tp_setattr */
#if PY_MAJOR_VERSION >= 3
    nullptr,                               /* tp_reserved */
#else
    (cmpfunc)nullptr,                     /* tp_compare */
#endif
    (reprfunc)nullptr,                    /* tp_repr */
    /* Method suites for standard classes */
    nullptr,                              /* tp_as_number */
    nullptr,                              /* tp_as_sequence */
    nullptr,                              /* tp_as_mapping */
    /* More standard operations (here for binary compatibility) */
    (hashfunc)nullptr,                    /* tp_hash */
    (ternaryfunc)nullptr,                 /* tp_call */
    (reprfunc)nullptr,                    /* tp_str */
    (getattrofunc)nullptr,                /* tp_getattro */
    (setattrofunc)nullptr,                /* tp_setattro */
    /* Functions to access object as input/output buffer */
    nullptr,                              /* tp_as_buffer */
    /* Flags to define presence of optional/expanded features */
    Py_TPFLAGS_DEFAULT,             /* tp_flags */
    User2__doc__,         /* tp_doc */
    /* Assigned meaning in release 2.0 */
    /* call function for all accessible objects */
    (traverseproc)nullptr,                /* tp_traverse */
    /* delete references to contained objects */
    (inquiry)nullptr,                     /* tp_clear */
    /* Assigned meaning in release 2.1 */
    /* rich comparisons */
    (richcmpfunc)nullptr,                 /* tp_richcompare */
    /* weak reference enabler */
    0,                              /* tp_weaklistoffset */
    /* Added in release 2.2 */
    /* Iterators */
    (getiterfunc)nullptr,                 /* tp_iter */
    (iternextfunc)nullptr,                /* tp_iternext */
    /* Attribute descriptor and subclassing stuff */
    PY_User2_methods,                             /* tp_methods */
    nullptr,                              /* tp_members */
    nullptr,                             /* tp_getset */
    nullptr,                              /* tp_base */
    nullptr,                              /* tp_dict */
    (descrgetfunc)nullptr,                /* tp_descr_get */
    (descrsetfunc)nullptr,                /* tp_descr_set */
    0,                              /* tp_dictoffset */
    (initproc)0,                   /* tp_init */
    (allocfunc)nullptr,                  /* tp_alloc */
    (newfunc)nullptr,                    /* tp_new */
    (freefunc)nullptr,                   /* tp_free */
    (inquiry)nullptr,                     /* tp_is_gc */
    nullptr,                              /* tp_bases */
    nullptr,                              /* tp_mro */
    nullptr,                              /* tp_cache */
    nullptr,                              /* tp_subclasses */
    nullptr,                              /* tp_weaklist */
    (destructor)PY_User2_tp_del,                 /* tp_del */
    0,                              /* tp_version_tag */
#if PY_MAJOR_VERSION >= 3
    (destructor)nullptr,                  /* tp_finalize */
#endif
};
#endif // ifdef USE_USER2
