// pytypedefsmodule.hpp
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
#ifndef PYTYPEDEFSMODULE_HPP
#define PYTYPEDEFSMODULE_HPP

#include <Python.h>

// cxx_header
#include "typedefs.h"

// splicer begin header.include
// splicer end header.include

// splicer begin header.C_declaration
// splicer end header.C_declaration

extern PyObject *PY_error_obj;

#if PY_MAJOR_VERSION >= 3
extern "C" PyMODINIT_FUNC PyInit_typedefs(void);
#else
extern "C" PyMODINIT_FUNC inittypedefs(void);
#endif

#endif  /* PYTYPEDEFSMODULE_HPP */
