! wrapferror.f
! This file is generated by Shroud nowrite-version. Do not edit.
! Copyright Shroud Project Developers. See LICENSE file for details.
!
! SPDX-License-Identifier: (BSD-3-Clause)
!
!>
!! \file wrapferror.f
!! \brief Shroud generated wrapper for error library
!<
! splicer begin file_top
! splicer end file_top
module error_mod
    use iso_c_binding, only : C_INT64_T
    ! splicer begin module_use
    ! splicer end module_use
    implicit none

    ! splicer begin module_top
    ! splicer end module_top

    ! typedef IndexType
    ! splicer begin typedef.IndexType
    integer, parameter :: index_type = C_INT64_T
    ! splicer end typedef.IndexType

    ! splicer begin additional_declarations
    ! splicer end additional_declarations

contains

    ! splicer begin additional_functions
    ! splicer end additional_functions

end module error_mod
