# Copyright Shroud Project Developers. See LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)
#
# Compile the RCA example ( Reference Count )
#
# make tester
#

testdir = tester

F_OBJS = \
    fmain.o \
    fpart.o

C_OBJS = \
    cpart.o

fmain.o : fpart.o

include ../../run/defaults.mk
