// wrapwrapped_inner2.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright Shroud Project Developers. See LICENSE file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wrapwrapped_inner2.h
 * \brief Shroud generated wrapper for inner2 namespace
 */
// For C users and C++ implementation

#ifndef WRAPWRAPPED_INNER2_H
#define WRAPWRAPPED_INNER2_H

// shroud
#include "typeswrapped.h"

// splicer begin namespace.inner2.CXX_declarations
// splicer end namespace.inner2.CXX_declarations

#ifdef __cplusplus
extern "C" {
#endif

// splicer begin namespace.inner2.C_declarations
// splicer end namespace.inner2.C_declarations

void WWW_inner2_worker(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPWRAPPED_INNER2_H
