// wraplibrary_outer1.h
// This file is generated by Shroud nowrite-version. Do not edit.
// Copyright (c) 2017-2024, Lawrence Livermore National Security, LLC and
// other Shroud Project Developers.
// See the top-level COPYRIGHT file for details.
//
// SPDX-License-Identifier: (BSD-3-Clause)
//
/**
 * \file wraplibrary_outer1.h
 * \brief Shroud generated wrapper for outer1 namespace
 */
// For C users and C++ implementation

#ifndef WRAPLIBRARY_OUTER1_H
#define WRAPLIBRARY_OUTER1_H

// shroud
#include "typeslibrary.h"


#ifdef __cplusplus
extern "C" {
#endif


void LIB_outer1_outer_func(void);

#ifdef __cplusplus
}
#endif

#endif  // WRAPLIBRARY_OUTER1_H
